### ISSUE TITLE
As a developer, I want to create a frontend for viewing Database entries

### ISSUE THREAD

**Issue by Sterberino** [CS180-spring/cs180-22-theboys#11]
Priority: 2

The frontend will be created using ReactJS. The following is required:
-Page must make fetch request to the server side code to retrieve products.
-Frontend must display all relevant data for individual product entries: Title, Seller, Image, Description, etc.

User Story: #7

Reviewer: Adrian

**Comment by adrianram12** [comment]
Frontend is completed. Just need to verify that database connections is successful.
